package ModuloVentas;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import DBCon.Conexion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Andres Ortega
 */
public class NuevaVentaForm extends javax.swing.JFrame {

    /**
     * Creates new form NuevaVentaForm
     */
    public NuevaVentaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boxServicio1 = new javax.swing.JCheckBox();
        boxServicio2 = new javax.swing.JCheckBox();
        boxServicio3 = new javax.swing.JCheckBox();
        boxServicio4 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboBoxEmpleados = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboBoxMetodosPago = new javax.swing.JComboBox<>();
        btnPagar = new javax.swing.JButton();

        setTitle("Nueva Factura");

        jLabel1.setText("Servicios:");

        boxServicio1.setText("Servicio 1");

        boxServicio2.setText("Servicio 2");

        boxServicio3.setText("Servicio 3");

        boxServicio4.setText("Servicio 4");

        jLabel2.setText("Cliente: ");

        jLabel3.setText("Empleado: ");

        comboBoxEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado 1", "Empleado 2", "Empleado 3", "Empleado 4", "Administrador" }));

        jLabel4.setText("Metodo de Pago: ");

        comboBoxMetodosPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta Credito/Debito", "Tarjeta de Regalo", "Efectivo" }));

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPagar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(boxServicio1)
                                .addGap(18, 18, 18)
                                .addComponent(boxServicio2)
                                .addGap(18, 18, 18)
                                .addComponent(boxServicio3)
                                .addGap(18, 18, 18)
                                .addComponent(boxServicio4))
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxMetodosPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(boxServicio1)
                    .addComponent(boxServicio2)
                    .addComponent(boxServicio3)
                    .addComponent(boxServicio4))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboBoxMetodosPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPagar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        String servicios = "";
        int total = 0;
        Connection con = null;
        try {
            if (boxServicio1.isSelected()) {
                servicios += boxServicio1.getText() + " - ";
                total += 1000;
            }
            if (boxServicio2.isSelected()) {
                servicios += boxServicio2.getText() + " - ";
                total += 500;
            }
            if (boxServicio3.isSelected()) {
                servicios += boxServicio3.getText() + " - ";
                total += 2000;
            }
            if (boxServicio4.isSelected()) {
                servicios += boxServicio4.getText() + " - ";
                total += 5000;
            }
            int valor = JOptionPane.showConfirmDialog(null, "Servicios: " + servicios
                    + "\nCliente: " + txtCliente.getText()
                    + "\nEmpleado:" + comboBoxEmpleados.getSelectedItem().toString()
                    + "\nMetodo de Pago: " + comboBoxMetodosPago.getSelectedItem().toString()
                    + "\nTotal: " + total,
                    "CONFIRMAR VENTA", JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.INFORMATION_MESSAGE);
            switch (valor) {
                case 0:
                    con = Conexion.getConnection();
                    PreparedStatement ps = con.prepareStatement("INSERT INTO Ventas"
                            + " (montoFacturado, productos, metodoPago, cliente, vendedor, fechaVenta)"
                            + " VALUES (?, ?, ?, ?, ?, ?)");
                    ps.setString(1, String.valueOf(total));
                    ps.setString(2, servicios);
                    ps.setString(3, comboBoxMetodosPago.getSelectedItem().toString());
                    ps.setString(4, txtCliente.getText());
                    ps.setString(5, comboBoxEmpleados.getSelectedItem().toString());
                    ps.setString(6, LocalDate.now().toString());
                    if (ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(null, "Gracias por su compra");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error en la factura");
                    }
                    con.close();
                case 1:
                    break;
                default:
                    break;

            }
        } catch (Exception e) {

        }


    }//GEN-LAST:event_btnPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaVentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaVentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaVentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaVentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaVentaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxServicio1;
    private javax.swing.JCheckBox boxServicio2;
    private javax.swing.JCheckBox boxServicio3;
    private javax.swing.JCheckBox boxServicio4;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> comboBoxEmpleados;
    private javax.swing.JComboBox<String> comboBoxMetodosPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCliente;
    // End of variables declaration//GEN-END:variables
}
